# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_auto_20161111_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='menu_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
